### ISSUE TITLE
Potential support for TT Oxford's other game? (Super Monkey Ball Adventure)

### ISSUE THREAD

**Issue by SonikkuA-DatH** [Smartkin/twinsanity-editor#5]
Super Monkey Ball Adventure (2006) notably uses the same BH/BD and MB/MH formats for the PS2 and PSP versions. Twinsanity HackPack can extract the BD archive to reveal the rest of the files. Interestingly it doesn't use RM2/SMX, instead RM and SM, and the editor (this and Neo Kesha's) can't read those
If you're interested, I can send the files

**Comment by NeoKesha** [comment]
That's unlikely, we have hard times supporting Beta-versions of Twinsanity and other consoles besides PS2. And have Editor able to load PS2-Release version of Twinsanity, that is still lacking a lot of features and polish.
Best thing you can do - fork repository and make SMB Editor. I am sure that's not that hard how it sounds.

**Comment by TheBetaM** [comment]
I've implemented basic support for viewing and editing chunks of the PSP version of the game. PS2 chunks remain inaccessible for now due to them being compressed.

**Comment by SonikkuA-DatH** [comment]
Woah, didn't expect this to be reopened
Thanks BetaM!

**Comment by TheBetaM** [comment]
PS2 chunks are now viewable along with all models, textures and sounds.
